CREATE TABLE COMPANY (
COMPANY_PK VARCHAR(20),
COMPANY_NAME VARCHAR(20),
PRIMARY KEY (COMPANY_PK)
);
CREATE TABLE CAR (
CAR_PK VARCHAR(20),
CAR_NAME VARCHAR(20),
COMPANY_FK VARCHAR(20),
PRIMARY KEY (CAR_PK),
FOREIGN KEY (COMPANY_FK) REFERENCES COMPANY(COMPANY_PK)
);
CREATE TABLE YEAR_TABLE(
YEAR_PK VARCHAR(20),
PRIMARY KEY (YEAR_PK)
);
CREATE TABLE OPTION_TABLE(
OPTION_PK VARCHAR(20),
OPTION_NAME VARCHAR(20),
PRIMARY KEY (OPTION_PK)
);
CREATE TABLE CAR_INFO(
CAR_INFO_PK VARCHAR(20),
CAR_FK VARCHAR(20),
YEAR_FK VARCHAR(20),
COMPANY_FK VARCHAR(20),
PRIMARY KEY (CAR_INFO_PK),
FOREIGN KEY (CAR_FK) REFERENCES CAR(CAR_PK),
FOREIGN KEY (YEAR_FK) REFERENCES YEAR_TABLE(YEAR_PK),
FOREIGN KEY (COMPANY_FK) REFERENCES COMPANY(COMPANY_PK)
);
CREATE TABLE CAR_OPTION (
CAR_OPTION_PK VARCHAR(20),
CAR_INFO_FK VARCHAR(20),
OPTION_FK VARCHAR(20),
PRIMARY KEY (CAR_OPTION_PK),
FOREIGN KEY (CAR_INFO_FK) REFERENCES CAR_INFO(CAR_INFO_PK),
FOREIGN KEY (OPTION_FK) REFERENCES OPTION_TABLE(OPTION_PK)
);