SELECT COM.COMPANY_NAME , CAR_NAME , YEAR_PK , GROUP_CONCAT(OT.OPTION_NAME ORDER BY OT.OPTION_NAME SEPARATOR ', ') AS OPTIONS
FROM COMPANY COM
JOIN CAR ON COM.COMPANY_PK = CAR.COMPANY_FK
JOIN CAR_OPTION CO ON CAR.CAR_PK = CO.CAR_FK
JOIN YEAR_TABLE Y ON CO.YEAR_FK = Y.YEAR_PK
JOIN OPTION_TABLE OT ON CO.OPTION_FK = OT.OPTION_PK
GROUP BY COM.COMPANY_NAME , CAR.CAR_NAME , Y.YEAR_PK
