SELECT 
    u.USER_NAME AS USERNAME,
    u.USER_AGE AS AGE,
    g.GENDER_NAME AS GENDERNAME,
    COUNT(uh.HOBBY_FK) AS HOBBY_COUNT,
    an.ADDRESS_NAME AS ADDRESS_NAME
FROM USER_TABLE u
JOIN GENDER g ON u.GENDER_FK = g.GENDER_PK
LEFT JOIN USER_HOBBY uh ON u.USER_PK = uh.USER_FK
JOIN USER_INFO ui ON u.USER_PK = ui.USER_FK
JOIN ADDRESS a ON ui.ADDRESS_FK = a.ADDRESS_PK
JOIN ADDRESS_NAME an ON a.ADDRESS_NAME_FK = an.ADDRESS_NAME_PK
GROUP BY u.USER_NAME, u.USER_AGE, g.GENDER_NAME, an.ADDRESS_NAME;