SELECT 
    UT.USER_NAME AS USERNAME,
    UT.USER_AGE AS AGE,
    G.GENDER_NAME AS GENDERNAME,
    COUNT(UH.HOBBY_FK) AS HOBBY_COUNT,
    AN.ADDRESS_NAME AS ADDRESS_NAME
FROM USER_TABLE UT
JOIN GENDER G ON UT.GENDER_FK = G.GENDER_PK
LEFT JOIN USER_HOBBY UH ON UT.USER_PK = UH.USER_FK
JOIN USER_INFO UI ON UT.USER_PK = UI.USER_FK
JOIN ADDRESS A ON UI.ADDRESS_FK = A.ADDRESS_PK
JOIN ADDRESS_NAME AN ON A.ADDRESS_NAME_FK = AN.ADDRESS_NAME_PK
GROUP BY UT.USER_NAME, UT.USER_AGE, G.GENDER_NAME, AN.ADDRESS_NAME;